In [60]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

In [399]:
path='go.jpg'
img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
img[180,129]

188

<div class="alert alert-warning" role="alert" style="font-size: 20px; font-weight: bold;">
  Exercice 1 : Préparation de l'Environnement
</div>


In [400]:
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

<div class="alert alert-warning" role="alert" style="font-size: 20px; font-weight: bold;">
  Exercice 2 : Comprendre et Manipuler les Pixels

</div>


In [401]:
def show_pixel(x,y,path):
    
    img=cv2.imread(path)
    imgpixel=np.array(img)
    
    return imgpixel[x,y]
    
show_pixel(90,60,'img.png')

array([1, 0, 4], dtype=uint8)

In [402]:
def to_pair(img):
    img=img-img%2
    return img
to_pair(img)

array([[46, 46, 46, ..., 62, 62, 62],
       [46, 46, 46, ..., 62, 62, 62],
       [46, 46, 46, ..., 64, 64, 64],
       ...,
       [10, 12, 16, ..., 10, 10,  8],
       [14, 14, 14, ..., 10, 10,  8],
       [18, 18, 16, ..., 10, 10,  8]], dtype=uint8)

<div class="alert alert-warning" role="alert" style="font-size: 20px; font-weight: bold;">

Question 3.1 : Écrivez une fonction pour convertir un texte en binaire.

</div>


In [403]:
message='Coded Message'

In [413]:
def texte_en_binaire(message):
    result = ' '.join(format(ord(char), '08b') for char in message)
    return result
msg=texte_en_binaire(message)
msg=msg.replace(' ','')

In [414]:
msg

'01000011011011110110010001100101011001000010000001001101011001010111001101110011011000010110011101100101'

In [550]:
def code_msg(img, msg):
    img = to_pair(img)
    cmt_len_msg = 0

    for i in range(len(img)):
        for j in range(len(img[1])):
            if cmt_len_msg < len(msg):
                
                img[i, j] += int(msg[cmt_len_msg])
                
                cmt_len_msg += 1
            else:
                break
    return img


In [573]:
img=code_msg(img,msg)
img

array([[46, 47, 46, ..., 62, 62, 62],
       [46, 46, 46, ..., 62, 62, 62],
       [46, 46, 46, ..., 64, 64, 64],
       ...,
       [10, 12, 16, ..., 10, 10,  8],
       [14, 14, 14, ..., 10, 10,  8],
       [18, 18, 16, ..., 10, 10,  8]], dtype=uint8)

In [576]:

def decode_msg(img):
    lest=[]
    cmt_len=0
    for i in range(len(img)):
        for j in range(len(img[1])):
            if cmt_len<len(msg):
                
                lest.append(img[i,j])
                cmt_len+=1
            else:
                break
    return np.array(lest)%2

In [577]:
result_list = decode_msg(img)
result_string = ''.join(map(str, result_list))
result_string = result_string.replace(',', '').replace(' ', '')

In [578]:
result_string

'01000011011011110110010001100101011001000010000001001101011001010111001101110011011000010110011101100101'

In [579]:
def binaire_to_chaine(binaire):
    
    octets = [binaire[i:i+8] for i in range(0, len(binaire), 8)]
    caracteres = ''.join([chr(int(octet, 2)) for octet in octets])

    return caracteres
binaire_to_chaine(result_string)

'Coded Message'