<div class="alert alert-block alert-info">
<b>Importation</b>
</div>

In [54]:
import numpy as np

<div class="alert alert-block alert-info">
<b>Créer un ndarray à partir du fichier STATISTIQUES_EQUIPE_LIGUE1.csv et vérifier le nombre 
de lignes et de colonnes.</b>
</div>

In [55]:
equipe=np.genfromtxt('STATISTIQUES_EQUIPE_LIGUE1.csv', delimiter=';', dtype=None,encoding=None,names=True)

In [56]:
equipe.shape

(20,)

<div class="alert alert-block alert-info">
<b>Calculer le nombre moyen de buts par match</b>
</div>

In [57]:
butpour=sum(equipe["ButsPour"].astype('i'))

In [58]:
butpour

444

In [59]:
nbr_match=equipe["Victoire"][0].astype('i')+equipe["Nuls"][0].astype('i')+equipe["Defaites"][0].astype('i')

In [60]:
nbr_match

15

In [61]:
nbr_mo=butpour/((len(equipe["equipe"])*nbr_match)/2)

In [62]:
nbr_mo

2.96

<div class="alert alert-block alert-info">
<b>Calculer la valeur moyenne du nombre de points (3 points pour une victoire, 1 point pour un 
nul et 0 points pour une défaite)</b>
</div>

In [63]:
nbr_moypc=(equipe["Victoire"].astype('i')*3)+(equipe["Nuls"].astype('i'))

In [64]:
nbr_moypc

array([12,  8, 13, 13, 19, 36, 26, 28, 21, 30, 27, 14, 13, 20, 41, 17, 31,
       11, 16, 14], dtype=int32)

In [65]:
nbr_moyp=nbr_moypc.mean()

In [66]:
nbr_moyp

20.5

<div class="alert alert-block alert-info">
<b>Quelle équipe a le plus grand nombre de victoires ?</b>
</div>

In [67]:
maxvic=np.max(equipe["Victoire"].astype('i'))

In [68]:
maxvic

13

In [69]:
equipe["equipe"][np.where(equipe["Victoire"].astype('i')==maxvic)]

array(['PSG'], dtype='<U11')

<div class="alert alert-block alert-info">
<b>Quel est le club ayant inscrit le plus grand nombre de buts ?</b>
</div>

In [70]:
maxbut=np.max(equipe["ButsPour"].astype('i'))

In [71]:
maxbut

43

In [72]:
equipe["equipe"][np.where(equipe["ButsPour"].astype('i')==maxbut)]

array(['PSG'], dtype='<U11')

<div class="alert alert-block alert-info">
<b>Quelle équipe a le plus grand nombre de hors-jeux ?</b>
</div>

In [73]:
maxhors=np.max(equipe["HorsJeux"].astype('i'))

In [74]:
equipe["equipe"][np.where(equipe["HorsJeux"].astype('i')==maxhors)]

array(['PSG'], dtype='<U11')

<div class="alert alert-block alert-info">
<b> Quelle équipe possède la meilleure attaque et celle qui possède la meilleure défense.</b>
</div>

In [75]:
maxbut=equipe["ButsPour"]/(equipe["Victoire"]+equipe["Defaites"]+equipe["Nuls"])

In [76]:
np.max(maxbut)

2.8666666666666667

In [77]:
equipe["equipe"][np.where(np.max(maxbut)==maxbut)]

array(['PSG'], dtype='<U11')

<div class="alert alert-block alert-info">
<b>L'equipe qui possède la meilleure défense</b>
</div>

In [78]:
minbut=equipe["ButsContre"]/(equipe["Victoire"]+equipe["Defaites"]+equipe["Nuls"])

In [79]:
equipe["equipe"][np.where(min(minbut)==minbut)]

array(['PSG'], dtype='<U11')

<div class="alert alert-block alert-info">
<b>Trouver le nombre des équipes dont le nombre de buts marqués est inférieur à celui encaissés 
puis afficher le nom de ces équipes.</b>
</div>

In [80]:
nbr_8=equipe["ButsPour"].astype('i')>equipe["ButsContre"].astype('i')

In [81]:
np.count_nonzero(nbr_8)

8

In [82]:
equipe["equipe"][nbr_8]

array(['Lens', 'Lille', 'Lorient', 'Lyon', 'Marseille', 'Monaco', 'PSG',
       'Rennes'], dtype='<U11')

<div class="alert alert-block alert-info">
<b>Calculer ensuite la différence de buts (buts pour - buts contre)
</b>
</div>

In [352]:
q_9=equipe["ButsPour"]-equipe["ButsContre"]
q_9


array([-10, -19, -17, -12,  -4,  16,   4,   5,   5,  13,   8,  -5,  -7,
        -2,  34,  -5,  17,  -9,  -7,  -5])

<div class="alert alert-block alert-info">
<b>Calculer pour chaque créneau horaire le pourcentage de buts marqués pour chaque club.
</b>
</div>

In [418]:
j=[]
z=[]
for i in range(20):
    j.append(list(equipe[i]))
    z.append(list((j[i][10:17]/np.sum(j[i][10:17])*100)))
j
z=np.array(z)
z

array([[ 0.        ,  7.14285714, 35.71428571, 21.42857143, 21.42857143,
        14.28571429],
       [13.33333333,  6.66666667, 13.33333333, 13.33333333, 26.66666667,
        26.66666667],
       [21.42857143,  7.14285714, 14.28571429,  7.14285714, 21.42857143,
        28.57142857],
       [18.75      , 12.5       ,  6.25      , 18.75      , 31.25      ,
        12.5       ],
       [15.78947368,  0.        ,  5.26315789, 31.57894737, 21.05263158,
        26.31578947],
       [ 3.84615385, 15.38461538,  7.69230769, 19.23076923, 23.07692308,
        30.76923077],
       [14.81481481, 14.81481481, 25.92592593, 11.11111111, 14.81481481,
        18.51851852],
       [19.23076923, 15.38461538, 19.23076923, 26.92307692,  7.69230769,
        11.53846154],
       [13.04347826, 17.39130435, 13.04347826, 13.04347826, 21.73913043,
        21.73913043],
       [19.23076923,  3.84615385, 30.76923077, 15.38461538, 11.53846154,
        19.23076923],
       [10.34482759,  6.89655172, 24.13793103, 24.

<div class="alert alert-block alert-info">
<b>Joindre les tableaux nécessaires dans un seul ndarray (20, 17) avec les colonnes suivantes : 
club, points, Victoire, Nuls, Defaite, ButsPour, Butscontre, Différence, HorsJeux,
ButsParMatch, ButsEncaissésParMatch, pourcentageButsMarques_creneau
</b>
</div>

In [409]:
newarray=np.vstack((equipe["equipe"],equipe["Victoire"],equipe["Nuls"],equipe["ButsPour"],\
                    equipe["ButsContre"],equipe["Defaites"],equipe["HorsJeux"],nbr_moypc ,q_9,maxbut,minbut,z.T))

<div class="alert alert-block alert-info">
<b>Trier le tableau obtenu dans la question 11 selon le nombre des points.
</b>
</div>

In [410]:
newarray[newarray[:,7].astype('str').argsort()].T

array([['1.6', '0.9333333333333333', '14.285714285714285',
        '7.142857142857142', '23', '35.714285714285715', '0.0', '24',
        '14', '21.428571428571427', '12', '9', '3', '-10',
        '21.428571428571427', '3', 'Ajaccio'],
       ['2.2666666666666666', '1.0', '26.666666666666668',
        '6.666666666666667', '17', '13.333333333333334',
        '13.333333333333334', '34', '15', '13.333333333333334', '8',
        '11', '2', '-19', '26.666666666666668', '2', 'Angers'],
       ['2.066666666666667', '0.9333333333333333', '28.57142857142857',
        '7.142857142857142', '23', '14.285714285714285',
        '21.428571428571427', '31', '14', '7.142857142857142', '13', '8',
        '4', '-17', '21.428571428571427', '3', 'Auxerre'],
       ['1.8666666666666667', '1.0666666666666667', '12.5', '12.5', '26',
        '6.25', '18.75', '28', '16', '18.75', '13', '8', '4', '-12',
        '31.25', '3', 'Brest'],
       ['1.5333333333333334', '1.2666666666666666', '26.31578947368421',
      

<div class="alert alert-block alert-info">
<b>En utilisant la méthode corrcoef(), afficher la matrice de corrélation. Interpréter le résultat
obtenu.
</b>
</div>

In [417]:
c=np.corrcoef(tuple(newarray[1:].astype('f')),tuple(newarray[1:].astype('f')))
c

array([[ 1.        , -0.52492665,  0.84928131, ...,  0.2617433 ,
        -0.38100451, -0.04507879],
       [-0.52492665,  1.        , -0.43724388, ..., -0.07370303,
         0.0392405 ,  0.3194713 ],
       [ 0.84928131, -0.43724388,  1.        , ...,  0.16649627,
        -0.54176048,  0.0677635 ],
       ...,
       [ 0.2617433 , -0.07370303,  0.16649627, ...,  1.        ,
        -0.02253257, -0.37672113],
       [-0.38100451,  0.0392405 , -0.54176048, ..., -0.02253257,
         1.        , -0.14282088],
       [-0.04507879,  0.3194713 ,  0.0677635 , ..., -0.37672113,
        -0.14282088,  1.        ]])

<div class="alert alert-block alert-info">
<b>. Sauvegarder le tableau trié dans un fichier csv avec l’entête correspondant.</b>
</div>

In [ ]:
headerout="equipe;Victoire;Nuls;ButsPour;ButsContre;Defaites;HorsJeux;Nombre de points;Diffrence;ButsParMatch;ButsEncaissésParMatch"

In [416]:
np.savetxt('outfile1.csv',newarray.T, delimiter=';',fmt="%s",header=headerout)